services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  app:
    build: ./app
    container_name: fastapi-codeqa
    ports:
      - "8000:8000"
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_COLLECTION: codebase
    volumes:
      - ./app:/app
      - ./repos:/repos
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - qdrant

  # jupyter:
  #   image: jupyter/scipy-notebook
  #   container_name: codeqa-jupyter
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebooks:/home/jovyan/work
  #     - ./repos:/home/jovyan/repos
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   depends_on:
  #     - qdrant