services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi-codeqa
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=codebase
      - MODEL_PATH=/app/models/ggml-gpt4all-j-v1.3-groovy.bin
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - qdrant

  # jupyter:
  #   image: jupyter/scipy-notebook
  #   container_name: codeqa-jupyter
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebooks:/home/jovyan/work
  #     - ./repos:/home/jovyan/repos
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   depends_on:
  #     - qdrant